version: "2"
linters:
  enable:
    - govet
    - errorlint
    - misspell
    - revive
    - staticcheck
    - whitespace
  exclusions:
    presets:
      - comments
      - std-error-handling
formatters:
  enable:
    - gofmt
