/*
Pacstrap Action

Construct the target rootfs with pacstrap tool.

Yaml syntax:
 - action: pacstrap
   mirror: <url with placeholders>
   repositories: <list of repositories>

Mandatory properties:

 - mirror -- the full url for the repository, with placeholders for
   $arch and $repo as needed, as would be found in mirrorlist

Optional properties:
 - repositories -- list of repositories to use for packages selection.
   Properties for repositories are described below.

Yaml syntax for repositories:

 repositories:
   - name: repository name
     siglevel: signature checking settings (optional)
*/
package actions

import (
	"fmt"
	"os"
	"path"
	"path/filepath"

	"github.com/go-debos/debos"
	"github.com/go-debos/fakemachine"
)

const configOptionSection = `
[options]
GPGDir   = %[1]s/etc/pacman.d/gnupg/
HoldPkg  = pacman glibc
Architecture = auto
SigLevel = Required DatabaseOptional TrustAll
`

const configRepoSection = `

[%[1]s]
Include = %[2]s
`

const mirrorListTemplate = `
# Mirror list generated by pacstrap action of debos

Server = %s
`

type Repository struct {
	Name     string
	SigLevel string
}

type PacstrapAction struct {
	debos.BaseAction `yaml:",inline"`
	Mirror           string
	Repositories     []Repository
}

func NewPacstrapAction() *PacstrapAction {
	d := PacstrapAction{}

	// Note there is no default mirror
	// TODO: Make the mirror URL optional by using reflector (when
	//       present) to generate the mirrorlist
	d.Repositories = []Repository{
		Repository{ Name: "core" }, Repository{ Name: "extra" }, Repository{ Name: "community" } }

	return &d
}

func (d *PacstrapAction) PreMachine(context *debos.DebosContext, m *fakemachine.Machine, args *[]string) error {
	pacmandir := "/etc/pacman.d/gnupg"

	// Make the host's gnupg configuration (and keyrings)
	// available inside the fakemachine - that way we can use the
	// host keyring to speed up resolving public keys later
	if info, err := os.Stat(pacmandir); err == nil && info.IsDir() {
		m.AddVolume(pacmandir)
	}
	return nil
}

func (d *PacstrapAction) writePacmanConfig(context *debos.DebosContext, configPath, mirrorListPath string) error {
	f, err := os.OpenFile(configPath, os.O_RDWR|os.O_CREATE, 0644)
	if err != nil {
		return fmt.Errorf("Couldn't open pacman config: %v", err)
	}
	defer func() {
		f.Close()
		if err != nil {
			os.Remove(configPath)
		}
	}()

	_, err = f.WriteString(fmt.Sprintf(configOptionSection, context.Rootdir))
	if err != nil {
		return fmt.Errorf("Couldn't write pacman config: %v", err)
	}
	for _, r := range d.Repositories {
		if _, err = f.WriteString(fmt.Sprintf(configRepoSection, r.Name, mirrorListPath)); err != nil {
			return fmt.Errorf("Couldn't write to pacman config: %v", err)
		}
		if r.SigLevel != "" {
			if _, err = f.WriteString(fmt.Sprintf("SigLevel = %s\n", r.SigLevel)); err != nil {
				return fmt.Errorf("Couldn't write to pacman config: %v", err)
			}
		}
	}
	return nil
}

func (d *PacstrapAction) writeMirrorList(context *debos.DebosContext, mirrorListPath string) error {
	if err := os.MkdirAll(path.Dir(mirrorListPath), 0755); err != nil {
		return fmt.Errorf("Unable to make directory for mirror list: %v", err)
	}

	f, err := os.OpenFile(mirrorListPath, os.O_RDWR|os.O_CREATE, 0644)
	if err != nil {
		return fmt.Errorf("Couldn't open mirror list: %v", err)
	}
	defer func() {
		f.Close()
		if err != nil {
			os.Remove(mirrorListPath);
		}
	}()

	if _, err = f.WriteString(fmt.Sprintf(mirrorListTemplate, d.Mirror)); err != nil {
		return fmt.Errorf("Couldn't write to mirror list: %v", err)
	}
	return nil
}

func (d *PacstrapAction) Run(context *debos.DebosContext) error {
	d.LogStart()

	if d.Mirror == "" {
		return fmt.Errorf("No mirror set, aborting.")
	}
	if len(d.Repositories) == 0 {
		return fmt.Errorf("No repositories configured.")
	}

	configPath := path.Join(context.Scratchdir, "pacman.conf")
	mirrorListPath := path.Join(context.Rootdir, "/etc/pacman.d/mirrorlist")

	// Create config for pacstrap
	if err := d.writePacmanConfig(context, configPath, mirrorListPath); err != nil {
		return err
	}

	// Mirror list for pacstrap
	if err := d.writeMirrorList(context, mirrorListPath); err != nil {
		return err
	}

	// Run pacman-key
	// Note that the host's pacman/gnupg secrets are root-only,
	// and we want to avoid running fakemachine/debos as root. As
	// such, explicitly run pacman-key --init so that new set is
	// generated.
	cmdline := []string{"pacman-key", "--nocolor", "--config", configPath, "--init"}
	if err := (debos.Command{}.Run("Pacman-key", cmdline...)); err != nil {
		return fmt.Errorf("Couldn't init pacman keyring: %v", err)
	}

	// Kickstart the public keyring if we can, to avoid expensive
	// key retrieval
	const pubring string = "/etc/pacman.d/gnupg/pubring.gpg"
	if info, err := os.Stat(pubring); err == nil && !info.IsDir() {
		// Ignore possible error; this is an optimization
		// only, so we can continue
		debos.CopyFile(
			pubring,
			filepath.Join(context.Rootdir, pubring),
			0644)
	}

	// Run pacstrap
	cmdline = []string{"pacstrap", "-M", "-C", configPath, context.Rootdir}
	if err := (debos.Command{}.Run("Pacstrap", cmdline...)); err != nil {
		log := path.Join(context.Rootdir, "var/log/pacman.log")
		_ = debos.Command{}.Run("pacstrap.log", "cat", log)
		return err
	}

	// Remove pacstrap config
	os.Remove(configPath)

	return nil
}
